image:
  file: .gitpod/Dockerfile
tasks:
  - init:
      go install gotest.tools/gotestsum@latest

  - init: |
      cd custodial && go get && cd -
      cd sign-auth && go get && cd -
  - name: "[custodial] golang live"
    command: |
      cd custodial
      air

  - name: "[sign-auth] golang live"
    command: |
      cd custodial
      air
  
  - name: postgres
    command: |
      docker run --name="cosmos-wallet" --rm -d -p 5432:5432 \
      -e POSTGRES_PASSWORD=cosmos-wallet \
      -e POSTGRES_USER=cosmos-wallet \
      -e POSTGRES_DB=cosmos-wallet \
      postgres -c log_statement=all
      sleep 12
      docker exec -it cosmos-wallet psql -U cosmos-wallet
    
vscode:
  extensions:
    - golang.go